project:
  type: website
  render:
    - "*.qmd"
    - "!*-supp.qmd"
    - "*.md"
  resources:
    - "*-supp.qmd"

website:
  title: "ETC5512: Wild Caught Data"
  site-url: "https://wcd.numbat.space"
  navbar:
    background: "#006dae"
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - text: Discussion
        icon: chat-fill
        href: "https://learning.monash.edu/course/view.php?id=27257&section=58"
      - text: Moodle
        icon: mortarboard-fill
        href: "https://learning.monash.edu/course/view.php?id=27257"
    right:
      - icon: github
        href: https://github.com/numbats/wcd

date-format: "D MMMM YYYY"

format:
  html:
    theme: [cosmo, numbat.scss]
    highlight: textmate
    toc: true
    mainfont: "Fira Sans"
    html-math-method: katex
    include-in-header:
      file: header.html

execute:
  echo: false
  warning: false
  message: false
